insert into cines (estado, ciudad) values('Aguascalientes' ,'Aguascalientes');
insert into cines (estado, ciudad) values('Baja California' ,'Mexicali');
insert into cines (estado, ciudad) values('Baja California' ,'Tijuana');
insert into cines (estado, ciudad) values('Baja California Sur' ,'Cabo San Lucas');
insert into cines (estado, ciudad) values('Baja California Sur' ,'La Paz');
insert into cines (estado, ciudad) values('Baja California Sur' ,'San Jose del Cabo');
insert into cines (estado, ciudad) values('Campeche' ,'Cd. del Carmen');
insert into cines (estado, ciudad) values('CDMX' ,'Centro');
insert into cines (estado, ciudad) values('CDMX' ,'Nor oriente');
insert into cines (estado, ciudad) values('CDMX' ,'Norte');
insert into cines (estado, ciudad) values('CDMX' ,'Oriente');
insert into cines (estado, ciudad) values('CDMX' ,'Poniente');
insert into cines (estado, ciudad) values('CDMX' ,'Sur');
insert into cines (estado, ciudad) values('Chiapas' ,'Tapachula');
insert into cines (estado, ciudad) values('Chiapas' ,'Tuxtla');
insert into cines (estado, ciudad) values('Chihuahua' ,'Cd. Juarez');
insert into cines (estado, ciudad) values('Chihuahua' ,'Chihuahua');
insert into cines (estado, ciudad) values('Chihuahua' ,'Delicias');
insert into cines (estado, ciudad) values('Coahuila' ,'Matamoros');
insert into cines (estado, ciudad) values('Coahuila' ,'Monclova');
insert into cines (estado, ciudad) values('Coahuila' ,'Piedras Negras');
insert into cines (estado, ciudad) values('Coahuila' ,'Ramos Arizpe');
insert into cines (estado, ciudad) values('Coahuila' ,'Saltillo');
insert into cines (estado, ciudad) values('Coahuila' ,'San Pedro');
insert into cines (estado, ciudad) values('Coahuila','Torreon');
insert into cines (estado, ciudad) values('Colima' ,'Colima');
insert into cines (estado, ciudad) values('Durango' ,'Durango');
insert into cines (estado, ciudad) values('Durango' ,'Gomez Palacio');
insert into cines (estado, ciudad) values('Estado de Mexico' ,'Atlacomulco');
insert into cines (estado, ciudad) values('Estado de Mexico' ,'Lerma');
insert into cines (estado, ciudad) values('Estado de Mexico' ,'Metepec');
insert into cines (estado, ciudad) values('Estado de Mexico' ,'Toluca');
insert into cines (estado, ciudad) values('Guanajuato' ,'Cortazar');
insert into cines (estado, ciudad) values('Guanajuato' ,'Guanajuato');
insert into cines (estado, ciudad) values('Guanajuato' ,'Irapuato');
insert into cines (estado, ciudad) values('Guanajuato' ,'Leon');
insert into cines (estado, ciudad) values('Guanajuato' ,'Salamanca');
insert into cines (estado, ciudad) values('Guanajuato' ,'San Miguel de Allende');
insert into cines (estado, ciudad) values('Guerrero' ,'Acapulco');
insert into cines (estado, ciudad) values('Guerrero' ,'Zihuatanejo');
insert into cines (estado, ciudad) values('Hidalgo' ,'Pachuca');
insert into cines (estado, ciudad) values('Hidalgo' ,'Progreso de Obregon');
insert into cines (estado, ciudad) values('Hidalgo' ,'Tulancingo');
insert into cines (estado, ciudad) values('Jalisco' ,'Cd. Guzman');
insert into cines (estado, ciudad) values('Jalisco' ,'Guadalajara');
insert into cines (estado, ciudad) values('Jalisco' ,'Ocotlan');
insert into cines (estado, ciudad) values('Jalisco' ,'Puerto Vallarta');
insert into cines (estado, ciudad) values('Jalisco' ,'Tonala');
insert into cines (estado, ciudad) values('Michoacan' ,'La Piedad');
insert into cines (estado, ciudad) values('Michoacan' ,'Lazaro Cardenas');
insert into cines (estado, ciudad) values('Michoacan' ,'Morelia');
insert into cines (estado, ciudad) values('Michoacan' ,'Zamora');
insert into cines (estado, ciudad) values('Morelos' ,'Cuautla');
insert into cines (estado, ciudad) values('Morelos' ,'Cuernavaca');
insert into cines (estado, ciudad) values('Monterrey' ,'Apodaca');
insert into cines (estado, ciudad) values('Monterrey' ,'Escobedo');
insert into cines (estado, ciudad) values('Monterrey' ,'Guadalupe');
insert into cines (estado, ciudad) values('Monterrey' ,'Juarez');
insert into cines (estado, ciudad) values('Monterrey' ,'Monterrey');
insert into cines (estado, ciudad) values('Monterrey' ,'Salinas Victoria');
insert into cines (estado, ciudad) values('Monterrey' ,'San Nicolas');
insert into cines (estado, ciudad) values('Monterrey' ,'San Pedro');
insert into cines (estado, ciudad) values('Monterrey' ,'Santa Catarina');
insert into cines (estado, ciudad) values('Nayarit' ,'Tepic');
insert into cines (estado, ciudad) values('Oaxaca' ,'Oaxaca');
insert into cines (estado, ciudad) values('Oaxaca' ,'Salina Cruz');
insert into cines (estado, ciudad) values('Oaxaca' ,'Tuxtepec');
insert into cines (estado, ciudad) values('Puebla' ,'Puebla');
insert into cines (estado, ciudad) values('Queretaro' ,'Queretaro');
insert into cines (estado, ciudad) values('Queretaro' ,'San Juan del Rio ');
insert into cines (estado, ciudad) values('Quintana Roo' ,'Cancun');
insert into cines (estado, ciudad) values('Quintana Roo','Chetumal');
insert into cines (estado, ciudad) values('Quintana Roo' ,'Cozumel');
insert into cines (estado, ciudad) values('Quintana Roo' ,'Playa del Carmen');
insert into cines (estado, ciudad) values('San Luis Potosi' ,'Cd. Valles');
insert into cines (estado, ciudad) values('San Luis Potosi' ,'San Luis Potosi');
insert into cines (estado, ciudad) values('Sinaloa' ,'Culiacan');
insert into cines (estado, ciudad) values('Sinaloa' ,'Guamuchil');
insert into cines (estado, ciudad) values('Sinaloa' ,'Guasave');
insert into cines (estado, ciudad) values('Sinaloa' ,'Los Mochis');
insert into cines (estado, ciudad) values('Sinaloa' ,'Mazatlan');
insert into cines (estado, ciudad) values('Sonora' ,'Caborca');
insert into cines (estado, ciudad) values('Sonora' ,'Cananea');
insert into cines (estado, ciudad) values('Sonora' ,'Cd. Obregon');
insert into cines (estado, ciudad) values('Sonora' ,'Guaymas');
insert into cines (estado, ciudad) values('Sonora' ,'Hermosillo');
insert into cines (estado, ciudad) values('Sonora' ,'Nacozari de Garcia');
insert into cines (estado, ciudad) values('Sonora' ,'Navojoa');
insert into cines (estado, ciudad) values('Tabasco' ,'Cardenas');
insert into cines (estado, ciudad) values('Tabasco' ,'Huimanguillo');
insert into cines (estado, ciudad) values('Tabasco' ,'Villahermosa');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Cd. Mante');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Cd. Victoria');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Matamoros');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Nuevo Laredo');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Reynosa');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Rio Bravo');
insert into cines (estado, ciudad) values('Tamaulipas' ,'Tampico');
insert into cines (estado, ciudad) values('Tlaxcala' ,'Tlaxcala');
insert into cines (estado, ciudad) values('Veracruz' ,'Boca del Rio');
insert into cines (estado, ciudad) values('Veracruz' ,'Coatzacoalcos');
insert into cines (estado, ciudad) values('Veracruz' ,'Cordoba');
insert into cines (estado, ciudad) values('Veracruz' ,'Minatitlan');
insert into cines (estado, ciudad) values('Veracruz' ,'Orizaba');
insert into cines (estado, ciudad) values('Veracruz' ,'Panuco');
insert into cines (estado, ciudad) values('Veracruz' ,'Poza Rica');
insert into cines (estado, ciudad) values('Veracruz' ,'Veracruz');
insert into cines (estado, ciudad) values('Yucatan' ,'Merida');
insert into cines (estado, ciudad) values('Yucatan' ,'Tizimin');
insert into cines (estado, ciudad) values('Yucatan' ,'Valladolid');
insert into cines (estado, ciudad) values('Zacatecas' ,'Fresnillo');
insert into cines (estado, ciudad) values('Zacatecas' ,'Rio Grande');
insert into cines (estado, ciudad) values('Zacatecas' ,'Zacatecas');
